name: "Maa Dev Build"

on:
  push:
    branches:
      - dev
    paths:
      - src/MeoAssistant/**
      - src/MeoAssistantBuilder/**
      - src/MeoAsstGui/**
      - 3rdparty/**
      - include/**
      - MeoAssistantArknights.sln
  pull_request:
    paths:
      - src/MeoAssistant/**
      - src/MeoAssistantBuilder/**
      - src/MeoAsstGui/**
      - 3rdparty/**
      - include/**
      - MeoAssistantArknights.sln
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 6.0.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Run dev build task
        run: pwsh .\build.ps1 DevBuild

      - name: Read file name
        id: read_path
        run: pwsh .\read_path.ps1 ./artifacts MaaBundle*

      - name: Upload Artifacts 0
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.read_path.outputs.name_0 }}
          path: ${{ steps.read_path.outputs.path_0 }}

      - name: Upload Artifacts 1
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.read_path.outputs.name_1 }}
          path: ${{ steps.read_path.outputs.path_1 }}

      - name: Upload Artifacts 2
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.read_path.outputs.name_2 }}
          path: ${{ steps.read_path.outputs.path_2 }}
